# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tasks.proto", :syntax => :proto3) do
    add_message "tasks.AddTaskRequest" do
      optional :task, :message, 1, "tasks.Task"
    end
    add_message "tasks.AddTaskResponse" do
      optional :success, :bool, 1
    end
    add_message "tasks.DeleteTaskRequest" do
      optional :title, :string, 1
    end
    add_message "tasks.DeleteTaskResponse" do
      optional :success, :bool, 1
    end
    add_message "tasks.FinishTaskRequest" do
      optional :title, :string, 1
    end
    add_message "tasks.FinishTaskResponse" do
      optional :task, :message, 1, "tasks.Task"
    end
    add_message "tasks.GetTasksRequest" do
    end
    add_message "tasks.Task" do
      optional :title, :string, 1
      optional :description, :string, 2
      optional :done_at, :message, 3, "google.protobuf.Timestamp"
    end
  end
end

module Tasks
  AddTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.AddTaskRequest").msgclass
  AddTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.AddTaskResponse").msgclass
  DeleteTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.DeleteTaskRequest").msgclass
  DeleteTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.DeleteTaskResponse").msgclass
  FinishTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.FinishTaskRequest").msgclass
  FinishTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.FinishTaskResponse").msgclass
  GetTasksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.GetTasksRequest").msgclass
  Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tasks.Task").msgclass
end
