# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tasks.proto for package 'tasks'

require 'grpc'
require 'tasks_pb'

module Tasks
  module TasksService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tasks.TasksService'

      rpc :AddTask, ::Tasks::AddTaskRequest, ::Tasks::AddTaskResponse
      rpc :DeleteTask, ::Tasks::DeleteTaskRequest, ::Tasks::DeleteTaskResponse
      rpc :FinishTask, ::Tasks::FinishTaskRequest, ::Tasks::FinishTaskResponse
      rpc :GetTasks, ::Tasks::GetTasksRequest, stream(::Tasks::Task)
    end

    Stub = Service.rpc_stub_class
  end
end
